---
- name: loop register test
  gather_facts: no
  hosts: localhost
  tasks:
    - name: looping echo task
      shell: "echo this item : {{ item }}"
      loop:
        - one
        - two
      register: echo_results

    - name: show echo_results variable
      debug:
        msg: "STDOUT from previous task: {{ item.stdout }}"
      loop: "{{ echo_results.results }}"     
      
...      
