---
- name: use student.bash_env role playbook
  hosts: devservers
  vars:
    prompt_color: blue
    default_prompt: '[\u on \h in \W dir]\$ '
  pre_tasks:
    - name: ensure test user doesn't exist
      user:
        name: student2
        state: absent
        force: yes
        remove: yes
  
  roles:
    - student.bash_env

  post_tasks:
    - name: create the test user
      user:
        name: student2
        state: present
        password: "{{ 'redhat' | password_hash('sha512', 'mysecretsalt') }}"

...
