---
- name: use the fetch module to retrieve secure log files
  hosts: all
  remote_user: root
  tasks:
    - name: fetch the /var/log/secure log file from managed hosts
      fetch:
        src: /var/log/secure
        dest: secure-backups
        flat: no

...
