---
- name: Install and configure web service
  hosts: server*.lab.example.com
#  hosts: [server .lab.example.com
  serial: 2

  tasks:
    - name: import the web_tasks.yml taks file
      import_tasks: tasks/web_tasks.yml
    
    - name: import the firewall_tasks.yml
      import_tasks: tasks/firewall_tasks.yml

  handlers:
    - name: restart_httpd
      service:
        name: httpd
        state: restarted
