#!/bin/bash
#
# Copyright 2017 Red Hat, Inc.
#
# NAME
#     lab-projects-host - grading script for DO407 host patterns GE
#
# SYNOPSIS
#     lab-projects-host {setup|cleanup}
#
#        setup   - prepare the system for starting the lab
#        cleanup - perform post-lab cleanup (not comprehensive like reset)
#
# DESCRIPTION
#     This script, based on singular argument, does setup and cleanup for lab-patterns.
#
# CHANGELOG
#   * Fri Dec 07 2018 Chen Chang <cchang@redhat.com>
#   - Changes for 2.7 refresh
#   * Fri Jun 30 2017 Artur Glogowski <aglogows@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
runuser='runuser student -c'
ssh='ssh -o StrictHostKeyChecking=no'
scp='scp -q'
target='workstation'
# Conditional to make the script compatible with the
# demo version.
if [[ ${lab_demo_mode} == "demo" ]]; then
  env="demo"
else
  env="dev"
fi

labname='projects-host'
lab_dir="/home/student"
working_dir=${lab_dir}/projects-host
ansible_cfg_file=${working_dir}/ansible.cfg
ansible_hst_file1=${working_dir}/inventory1
ansible_hst_file2=${working_dir}/inventory2
ansible_user=devops

control_node='workstation'
ansible_target1=servera.lab.example.com
ansible_target2=serverb.lab.example.com
ansible_target3=serverc.lab.example.com
ansible_target4=serverd.lab.example.com

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
#declare -a valid_commands=(setup grade cleanup solve reset)
declare -a valid_commands=(setup cleanup)

function lab_setup {

  reqd_package='ansible'
  host_reachable ${control_node}
  host_reachable ${ansible_target1}
  host_reachable ${ansible_target2}
  host_reachable ${ansible_target3}
  host_reachable ${ansible_target4}

  print_header "Setting up ${control_node} for lab exercise work:"

  setup_check_ansible workstation

  setup_create_lab_dir $labname

  setup_download_ansible_cfg $labname

  pad ' · Downloading inventory1 file'
  _download_file inventory1 $labname

  pad ' · Downloading inventory2 file'
  _download_file inventory2 $labname

  pad ' · Downloading playbook.yml file'
  _download_file playbook.yml $labname

}


function lab_cleanup {

  echo
  echo "Cleaning up the lab on ${target}:"
  echo
  host_reachable ${target}
  print_SUCCESS

}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
