#!/bin/bash
#
# Copyright 2016 Red Hat, Inc.
#
# NAME
#     lab-intro-install - grading script for DO407 installation practice
#
# SYNOPSIS
#     lab-intro-install {setup|grade|cleanup|solve|reset}
#
#        solve   - do the lab exercise for the student (may call setup)
#        (ONLY INCLUDE PROVIDED COMMANDS, REMOVE REST)
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     cleanup, reset, or solve for the particular lab of awesomeness.
#
# CHANGELOG
#   * Tue Oct 23 2016 Chen Chang <cchang@redhat.com>
#   - Update for Ansible 2.7
#   * Mon May 16 2016 Chen Chang <cchang@redhat.com>
#   - Changes to align with new directory structure
#   * Mon May  2 2016 George Hacker <ghacker@redhat.com>
#   - Changed print_SUCCESS to print_PASS in lab_grade function
#   - Fixed quoting error
#   * Sun Apr  3 12:51:14 EDT 2016 Chen Chang <cchang@redhat.com>
#   - New script

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='workstation'

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup cleanup)

function lab_setup {

  print_header "Setting up environment the exercise:"
  pad " · Setup: "
  print_SUCCESS
  print_line
}

function lab_cleanup {

  print_header "Cleaning up environment:"

  pad " · Cleanup: "
  print_SUCCESS
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
