#!/bin/bash
#
# Copyright 2017 Red Hat, Inc.
#
# NAME
#     lab-deploy-review - grading script for DO407 deploy-review lab
#
# SYNOPSIS
#     lab-deploy {setup|grade|cleanup}
#
#        setup   - prepare the system for starting the lab exercise
#        grade   - perform evaluation steps on the system
#        cleanup - perform post-lab cleanup (not comprehensive like reset)
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     and cleanup for the DO407 review lab.
#
# CHANGELOG
#   * Fri Nov 2 2018 Victor Costea <vcostea@redhat.com>
#   - From lab-deploy updated for DO407 Ansible 2.7
#   * Thu Jul 6 2017 Artur Glogowski <aglogows@redhat.com>
#   - Modified to run in the new DO410 environment
#   * Mon May  2 2016 George Hacker <ghacker@redhat.com>
#   - Changed print_SUCCESS to print_PASS in lab_grade function
#   * Sun Apr  3 12:51:14 EDT 2016 Chen Chang <cchang@redhat.com>
#   - New script

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
targetw='workstation'
targeta='servera'
targetb='serverb'
targetc='serverc'
targetd='serverd'

labname='deploy-review'

lab_dir="/home/student/${labname}"
ansible_cfg="${lab_dir}/ansible.cfg"
ansible_inv="${lab_dir}/inventory"
ansible_static_inv="${lab_dir}/inventory/inventory"

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup grade cleanup)

function lab_setup {
  cd
  control_node=${targetw}

  # Check for lab prerequisites.
  reqd_package='ansible'

  print_header "Setting up ${control_node} for lab exercise work:"
  host_reachable ${targeta}
  host_reachable ${targetb}
  host_reachable ${targetc}
  host_reachable ${targetd}

  pad " · ${reqd_package} package is installed on ${control_node}"
  if rpm -q --quiet ${reqd_package}
  then
    print_SUCCESS
  else
    if yum install -y ${reqd_package} &> /dev/null
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi

  print_line
}

function lab_grade {

  target=${targetw}
  host_reachable ${targeta}
  host_reachable ${targetb}
  host_reachable ${targetc}
  host_reachable ${targetd}

  print_header "Grading the student's work on ${target}:"

  # Put in the steps to grade the lab (use print_PASS or print_FAIL)

  pad " · Verify active configuration file"
  cmd1="cd ${lab_dir}; ansible --version -v 2>&1 | awk -F' = ' '/config file/{print \\\$2}'"
  active_ansible_cfg=$(su - student -c "${ssh} ${target} \"${cmd1}\"")
  if [[ "${active_ansible_cfg}" == "${ansible_cfg}" ]]
  then
    print_PASS
  else
    print_FAIL
  fi
  
  pad " . Verify servera /etc/motd"
  cd ${lab_dir}; ansible servera.lab.example.com -m command -a 'cat /etc/motd'|grep -E "\<This server is managed by Ansible\>"
  if [[ $? == 0 ]]
  then
    print_PASS
  else
    print_FAIL
  fi

  pad " . Verify serverb /etc/motd"
  cd ${lab_dir}; ansible serverb.lab.example.com -m command -a 'cat /etc/motd'|grep -E "\<This server is managed by Ansible\>"
  if [[ $? == 0 ]]
  then
    print_PASS
  else
    print_FAIL
  fi

  pad " . Verify serverc /etc/motd"
  cd ${lab_dir}; ansible serverc.lab.example.com -m command -a 'cat /etc/motd'|grep -E "\<This server is managed by Ansible\>"
  if [[ $? == 0 ]]
  then
    print_PASS
  else
    print_FAIL
  fi
  pad " . Verify serverd /etc/motd"
  cd ${lab_dir}; ansible serverd.lab.example.com -m command -a 'cat /etc/motd'|grep -E "\<This server is managed by Ansible\>"
  if [[ $? == 0 ]]
  then
    print_PASS
  else
    print_FAIL
  fi

  # Overall grade
  print_line
  pad 'Overall lab grade'
  if [[ ${fail_count} -eq 0 ]]
  then
    print_PASS
  else
    print_FAIL
  fi

  print_line
}

function lab_cleanup {

  target=${targetw}
  host_reachable ${targeta}
  host_reachable ${targetb}
  host_reachable ${targetc}
  host_reachable ${targetd}

  print_header "Cleaning up the lab on ${targetw}:"
  pad ' · Restore /etc/motd'
  cmd1="ansible -i ${ansible_static_inv} all -m shell -a '> /etc/motd' -u devops -b --become-user root"
  su -  student -c "${ssh} ${target} \"${cmd1}\"" &> /dev/null
  print_SUCCESS

  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
