#!/bin/bash
#
# Copyright 2018 Red Hat, Inc.
#
# NAME
#     lab-projects-parallelism - grading script for DO407
#
# SYNOPSIS
#     lab-projects-parallelism {setup | cleanup}
#
#        setup   - prepare the system for starting the lab
#        cleanup - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does setup or
#     cleanup for a DO407 lab.
#
# CHANGELOG
#   * Mon Dec 10 2018 Chen Chang <cchang@redhat.com>
#   - Update for 2.7 release
#   * Wed Oct 24 2018 Victor Costea <vcostea@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
labname='projects-parallelism'
run_as_root='true'
target='workstation'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup cleanup)

function lab_setup {

  control_node=${target}

  print_header "Setting up ${control_node} for lab exercise work:"

  #From labtool.do407.shlib
  #Check Ansible is installed.
  setup_check_ansible ${target}

  #From labtool.do407.shlib
  #Create working directory for lab artifacts.
  setup_create_lab_dir $labname

  #From labtool.do407.shlib
  #Download ansible.cfg
  setup_download_ansible_cfg $labname

  #From labtool.do407.shlib
  #Download Ansible Inventory
  setup_download_inventory_file $labname

  pad ' · Deploying playbook.yml playbook'
  ##From labtool.do407.shlib
  _download_file playbook.yml $labname

  pad ' · Deploying remove_apache.yml playbook'
  ##From labtool.do407.shlib
  _download_file remove_apache.yml $labname

  pad ' · Remove apache'
  cd /home/student/${labname} && ansible-playbook remove-apache.yml
  print_SUCCESS  
 
  print_line
}

function lab_cleanup {
  echo
  echo "Cleaning up the lab on ${target}:"
  echo
  host_reachable ${target}

  pad ' · Remove apache'
  cd /home/student/${labname} && ansible-playbook remove-apache.yml
  print_SUCCESS  

  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
