#!/bin/bash
#
# Copyright 2018 Red Hat, Inc.
#
# NAME
#     lab-system-storage - setup script for DO407 Admin Storage practice exercise
#
# SYNOPSIS
#     lab-system-storage {setup|cleanup}
#
#        setup   - create working directory with inventory and templates
#        cleanup - remove changes applied to managed hosts
#
# DESCRIPTION
#     This script creates a playbook project populated with an
#     ansible.cfg file, inventory file, skeleton playbook, and variables
#     file.  Students will modify the playbook file to create partitions,
#     volume groups, logical volumes, and mount points on the remote host.
#
#     This script is also used to cleanup partitions, volume groups, and
#     logical volumes, and mount points created during the exercise.
#
# CHANGELOG
#   * Thu Dec 13 2018 Dan Kolepp <dkolepp@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
runuser='runuser student -c'

control_node='workstation'

# Conditional to make the script compatible with the
# demo version.
if [[ ${lab_demo_mode} == "demo" ]]; then
  env="demo"
else
  env="dev"
fi

labname="system-storage"
working_dir="/home/student/${labname}"
ansible_cfg_file="${working_dir}/ansible.cfg"
ansible_hst_file="${working_dir}/inventory"
ansible_playbook_file="${working_dir}/storage.yml"
vars_file="${working_dir}/storage_vars.yml"
ansible_user='devops'
ansible_target='servera.lab.example.com'

file_list=(storage.yml storage_vars.yml)

materials='http://materials.example.com'

declare -a valid_commands=(setup cleanup)

function lab_setup {


  print_line
  print_line "Setting up ${control_node} for Guided Exercise ($labname):"
  print_line

  #From labtool.do407.shlib
  #Check Ansible is installed.
  setup_check_ansible workstation

  #From labtool.do407.shlib
  #Create working directory for lab artifacts.
  setup_create_lab_dir $labname

  #From labtool.do407.shlib
  #Download Ansible Inventory
  setup_download_inventory_file $labname

  #From labtool.do407.shlib
  #Download ansible.cfg
  setup_download_ansible_cfg $labname

  for file in ${file_list[@]}
  do
      pad " · Downloading $file file"
      _download_file $file $labname
  done

}



function lab_cleanup {

  print_header "Cleaning up for Guided Exercise ($labname):"

  host_reachable ${ansible_target}

  pad ' · Running a cleanup playbook'
  run_a_playbook $labname cleanup.yml

  echo
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
